# Generated by Django 3.2.17 on 2023-02-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('founder', models.CharField(max_length=50)),
                ('established_date', models.DateField()),
                ('company_contact', models.CharField(max_length=12)),
                ('company_mail', models.EmailField(max_length=254, unique=True)),
                ('company_password', models.CharField(max_length=20)),
                ('company_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_id', models.CharField(max_length=50)),
                ('Branch_name', models.CharField(max_length=50)),
                ('Branch_lat', models.FloatField()),
                ('Branch_long', models.FloatField()),
                ('Branch_range', models.IntegerField()),
                ('is_main', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'unique_together': {('Branch_id', 'company')},
                'index_together': {('Branch_id', 'company')},
            },
        ),
    ]
